import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NewSidebar from "@/components/new-sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Organizer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
        >
            <NewSidebar />
            <div className="flex-1 p-3 bg-neutral-950">
                <div className="w-full h-full bg-neutral-900 p-6 rounded-lg">
                    {children}
                </div>
            </div>
        </div>
    );
}
