import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NewSidebar from "@/components/new-sidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Organizer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col md:flex-row h-dvh w-screen bg-neutral-950 text-neutral-200 overflow-hidden`}
        >
            <NewSidebar />
            <div className="flex-1 min-h-0 p-2 w-full">
                <div className="w-full h-full rounded-lg bg-neutral-900 p-4">
                    {children}
                </div>
            </div>
        </div>
    );
}
